
class RGB_slopes_sensor_config_LED_Setting_temp:

    # All the slopes and intercepts are stored in dictionaries
    # A string combining configuration, LED Setting and temperature is generated
    # The string is used as a key to store the values in the dictionary
    red_slope   = {}
    green_slope = {}
    blue_slope  = {}

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 44C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_44C'] = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_44C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_44C'] = 1

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 48C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_48C']   = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_48C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_48C']  = 1

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 56C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_56C']   = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_56C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_56C']  = 1

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 62C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_62C'] = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_62C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_62C'] = 1

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 68C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_68C']   = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_68C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_68C']  = 1

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 74C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_74C'] = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_74C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_74C'] = 1

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 80C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_80C']   = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_80C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_80C']  = 1

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 86C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_86C'] = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_86C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_86C'] = 1

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 92C
    red_slope['32ms_4X_LED_Setting_0,3,5,6_temp_92C']   = 1
    green_slope['32ms_4X_LED_Setting_0,3,5,6_temp_92C'] = 1
    blue_slope['32ms_4X_LED_Setting_0,3,5,6_temp_92C']  = 1

    # The unique string is generated by combining the following in order
    # 1. Image sensor configuration : 32ms_4X
    # 2. LED Setting at which slope is computed  : 0,3,5,6
    # 3. Temperature at which the slope is computed: 48C, 56C, 68C, 80C, 92C
    # Then the string is formed combining the above three as follows
    # Generic: <1>_LED_Setting_<2>_temp_<3>
    # Example: 32ms_4X_LED_Setting_0,3,5,6_temp_48
    def ret_RGB_slope_at_config_LED_Setting_temp(self, unique_string ):
        return self.red_slope[unique_string], self.green_slope[unique_string], self.blue_slope[unique_string]
