
class RGB_intercepts_sensor_config_LED_Setting_temp:

    # All the slopes and intercepts are stored in dictionaries
    # A string combining configuration, LED Setting and temperature is generated
    # The string is used as a key to store the values in the dictionary
    red_intercept   = {}
    blue_intercept  = {}
    green_intercept = {}

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 44C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_44C']   = 0.889017235
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_44C'] = 0.759661611
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_44C']  = 0.428489496

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 48C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_48C']   = 1.223329683
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_48C'] = 1.069457459
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_48C']  = 0.634916841

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 56C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_56C']   = 2.3164
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_56C'] = 2.1196
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_56C']  = 1.3940

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 62C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_62C']   = 3.739040596
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_62C'] = 3.540504742
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_62C']  = 2.514404704

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 68C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_68C']   = 6.0355
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_68C'] = 5.9139
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_68C']  = 4.5352

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 74C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_74C']   = 9.581867928
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_74C'] = 9.040244583
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_74C']  = 7.368009556

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 80C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_80C']   = 15.2120
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_80C'] = 13.8190
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_80C']  = 11.9702

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 86C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_86C']   = 24.77651277
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_86C'] = 23.90452842
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_86C']  = 21.6705623

    # Sensor_Config = 32ms_4X, LED_Setting = 0,3,5,6 Temperature = 92C
    red_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_92C']   = 40.3545
    green_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_92C'] = 41.3505
    blue_intercept['32ms_4X_LED_Setting_0,3,5,6_temp_92C']  = 39.2318

    # The unique string is generated by combining the following in order
    # 1. Image sensor configuration : 32ms_4X
    # 2. LED Setting used to compute intercept : 0,3,5,6
    # 3. Temperature at which the intercept is needed: 48C, 56C, 68C, 80C, 92C
    # Then the string is formed combining the above three as follows
    # Generic: <1>_LED_Setting_<2>_temp_<3>
    # Example: 32ms_4X_LED_Setting_0,3,5,6_temp_48
    def ret_RGB_intercept_at_config_LED_Setting_temp(self, unique_string ):
        return self.red_intercept[unique_string], self.green_intercept[unique_string], self.blue_intercept[unique_string]
